# PowerShell script to create Kubernetes secrets locally
# Fill in the values from your GitHub Secrets

$env:Path += ";C:\Users\basil\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kubectl_Microsoft.Winget.Source_8wekyb3d8bbwe"

# TODO: Fill in these values from GitHub Secrets
$SUPABASE_ANON_KEY = "YOUR_VALUE_HERE"
$SUPABASE_SERVICE_ROLE_KEY = "YOUR_VALUE_HERE"
$SUPABASE_DB_PASSWORD = "YOUR_VALUE_HERE"
$SUPABASE_PROJECT_ID = "YOUR_VALUE_HERE"
$ANTHROPIC_API_KEY = "YOUR_VALUE_HERE"
$OPENAI_API_KEY = "YOUR_VALUE_HERE"
$TOGETHER_API_KEY = "YOUR_VALUE_HERE"
$HUGGINGFACE_API_KEY = "YOUR_VALUE_HERE"
$HUGGING_FACE_ACCESS_TOKEN = "YOUR_VALUE_HERE"
$REPLICATE_API_TOKEN = "YOUR_VALUE_HERE"
$JINA_API_KEY = "YOUR_VALUE_HERE"
$FIRECRAWL_API_KEY = "YOUR_VALUE_HERE"
$JWT_SECRET_KEY = "YOUR_VALUE_HERE"
$ENCRYPTION_KEY = "YOUR_VALUE_HERE"
$MATERIAL_KAI_API_KEY = "YOUR_VALUE_HERE"
$MATERIAL_KAI_API_URL = "YOUR_VALUE_HERE"
$MATERIAL_KAI_WORKSPACE_ID = "YOUR_VALUE_HERE"
$MATERIAL_KAI_CLIENT_ID = "YOUR_VALUE_HERE"
$SENTRY_DSN = "https://73f48f6581b882c707ded429e384fb8a@o4509716458045440.ingest.de.sentry.io/4510132019658832"

kubectl create secret generic mivaa-secrets `
  --from-literal=SUPABASE_ANON_KEY="$SUPABASE_ANON_KEY" `
  --from-literal=SUPABASE_SERVICE_ROLE_KEY="$SUPABASE_SERVICE_ROLE_KEY" `
  --from-literal=SUPABASE_DB_PASSWORD="$SUPABASE_DB_PASSWORD" `
  --from-literal=SUPABASE_PROJECT_ID="$SUPABASE_PROJECT_ID" `
  --from-literal=ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" `
  --from-literal=OPENAI_API_KEY="$OPENAI_API_KEY" `
  --from-literal=TOGETHER_API_KEY="$TOGETHER_API_KEY" `
  --from-literal=HUGGINGFACE_API_KEY="$HUGGINGFACE_API_KEY" `
  --from-literal=HUGGING_FACE_ACCESS_TOKEN="$HUGGING_FACE_ACCESS_TOKEN" `
  --from-literal=REPLICATE_API_TOKEN="$REPLICATE_API_TOKEN" `
  --from-literal=JINA_API_KEY="$JINA_API_KEY" `
  --from-literal=FIRECRAWL_API_KEY="$FIRECRAWL_API_KEY" `
  --from-literal=JWT_SECRET_KEY="$JWT_SECRET_KEY" `
  --from-literal=ENCRYPTION_KEY="$ENCRYPTION_KEY" `
  --from-literal=MATERIAL_KAI_API_KEY="$MATERIAL_KAI_API_KEY" `
  --from-literal=MATERIAL_KAI_API_URL="$MATERIAL_KAI_API_URL" `
  --from-literal=MATERIAL_KAI_WORKSPACE_ID="$MATERIAL_KAI_WORKSPACE_ID" `
  --from-literal=MATERIAL_KAI_CLIENT_ID="$MATERIAL_KAI_CLIENT_ID" `
  --from-literal=SENTRY_DSN="$SENTRY_DSN" `
  --namespace=default `
  --dry-run=client -o yaml | kubectl apply -f -

Write-Host "✅ Secrets created successfully!"

